language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=
  - NODE_ENV=release
deploy:
  - provider: bluemixcloudfoundry
    edge: true
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    organization: $BLUEMIX_ORGANIZATION
    space: base-staging
    region: eu-gb
    on:
      branch: staging
  - provider: bluemixcloudfoundry
    edge: true
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    organization: $BLUEMIX_ORGANIZATION
    space: base-production
    region: eu-gb
    on:
      branch: master
